### ISSUE TITLE
Новый парсер 2

### ISSUE THREAD

**Issue by Oleh-Verhulenko** [Oleh-Verhulenko/Data-ht#4]
Создать новый парсер одного из сайтов за январь

**Comment by samusevalexunsued** [comment]
https://www.propertyfinder.eg/en/
http://joxi.ru/GrqKyXgT7wye2z

2 парсер закончен.

**Comment by samusevalexunsued** [comment]
Некоторая информация по парсерам и по сайтам источникам.
Когда выбираю сайты для парсинга я проверяю его по некоторым обязательным и необязательным критериям.
Обязательные:
1. На сайте должно быть уникальное поле (ид, урл или что-то еще). Без этого поля я могу спарсить сайт, но не смогу поставить его на постоянный парсинг, поскольку не буду знать парсил ли я уже объект и мне надо обновить информацию или это новый объект. На данный момент был только 1 сайт который я не парсил по этому критерию (у объекта не было ид, урл был динамический и не было никакого параметра для определения уникальности объекта).
2. Наличие некоторых полей без которых информация об объекте бесполезна. Это поля: цена (был сайт где цена выдавалась только по запросу, через форму обратной связи), контактные данные (телефон или емейл, без них объявление бесполезно, достаточное кол-во сайтов не отдает контактые данные).
3. Сайт должен соответствовать тематике. https://www.similarweb.com/top-websites/category/business-and-industry/real-estate в этом списке есть сайты о недвижимости, но на них нет объектов (сайты риелторских компаний без каталога, сайты  по поиску сожителей для съема и т.д.)

Необязательные (но на данный момент я все равно отсеиваю по этим критериям):
1. На сайте должно быть достаточное кол-во объектов (я отсеиваю сайты если на них нет хотя бы 5 тыс объявлений, такие сайты попадались).
2. У сайта должна быть английская версия. Я могу парсить сайты и без нее, но на разбор сайта без английской (или русской)  версии уйдет значительно большее кол-во времени.
