### ISSUE TITLE
Парсер - cian.ru

### ISSUE THREAD

**Issue by Oleh-Verhulenko** [Oleh-Verhulenko/Data-ht#6]
Проверить возможность обновления парсера с сайта cian.ru. Если обновление невозможно, то пересобрать его.
На выходе нужен ХМЛ файл для Афи.

**Comment by samusevalexunsued** [comment]
По этому сайту после рассмотрения могу сказать следующее:
Приблизительное время работы над парсером 3-4 дня (больше обычного поскольку очень много категорий надо будет перепроверить как по параметрам так и по соответствию нашим категориям). 
Судя по верстке (комментариям и общему состоянию), сайт активно пишется/дописывается, продолжительность работоспособности парсера неизвестна.
